// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1581934376);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1581934496);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581934616);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1581934256);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1581591139);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1581515796);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1581934136);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1580743993);
user_pref("browser.laterrun.bookkeeping.sessionCount", 20);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{916d95ea-0402-4907-9b74-710111678600}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1580860800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 1);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1581520720);
user_pref("browser.onboarding.notification.prompt-count", 4);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581934112588");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581937712588");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181212094312");
user_pref("browser.startup.homepage_override.mstone", "60.4.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1580743995176");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "60.4.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Fri, 14 Feb 2020 17:54:32 GMT");
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.cache.lastUpdate", 1581934377);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181212094312");
user_pref("extensions.lastAppVersion", "60.4.0");
user_pref("extensions.lastPlatformVersion", "60.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"0b66284f-e18a-433b-88c6-487a1f310127\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1581934352);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1581517306);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181212094312");
user_pref("media.gmp-manager.lastCheck", 1581934129);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1581430444);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "c263738a-4723-4b18-9aa9-3a9ec0bdb98a");
user_pref("services.blocklist.addons.checked", 1581934462);
user_pref("services.blocklist.clock_skew_seconds", 34);
user_pref("services.blocklist.gfx.checked", 1581934462);
user_pref("services.blocklist.last_etag", "\"1581882874409\"");
user_pref("services.blocklist.last_update_seconds", 1581934462);
user_pref("services.blocklist.onecrl.checked", 1581934462);
user_pref("services.blocklist.pinning.checked", 1581934462);
user_pref("services.blocklist.plugins.checked", 1581934462);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1580809042);
user_pref("toolkit.startup.last_success", 1581934105);
user_pref("toolkit.telemetry.cachedClientID", "cf01fca7-6daa-4b6e-9351-686727905fd1");
user_pref("toolkit.telemetry.previousBuildID", "20181212094312");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
